### ISSUE TITLE
Why I am getting import problem?

### ISSUE THREAD

**Issue by ashique992** [kevinheavey/solders#31] opened 2022-12-07 06:15 UTC
Hi Kevin,

I have import problem for solders. I am using Python 3.11.0 also i have tried 3.7 but same problem.

![image](https://user-images.githubusercontent.com/82217243/206102424-a01b15b3-565e-458c-944d-bb6c583e43c7.png)
![image](https://user-images.githubusercontent.com/82217243/206102749-596f05c5-e2e1-47f2-846a-eb8ddc93e43d.png)

Can you help me?

Thanks.

**Comment by kevinheavey** [comment] 2022-12-07 13:37
What error message are you getting?

**Comment by kevinheavey** [comment] 2022-12-12 12:50
@ashique992 let me know if you have any more information. I'll close this in a few days

**Comment by kevinheavey** [comment] 2022-12-15 11:40
Closing, feel free to reply and I'll reopen

**Closed by kevinheavey** 2022-12-15 11:40 UTC

**Comment by thekeviv** [comment] 2023-01-27 02:47
I also seem to be having the same issue. The other lib imports work fine.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/16347985/214999315-b5c1d417-a492-412e-ae63-ba1dbc34af46.png">
<img width="847" alt="image" src="https://user-images.githubusercontent.com/16347985/214999389-ab0eb2e3-be0a-4716-8f8a-c2e9f31a63e2.png">

**Comment by kevinheavey** [comment] 2023-01-27 11:51
@thekeviv Pyright complains about packages that are just Rust/C + .pyi files, such as Solders. Pyright still works fine and the complaining can be turned off, which I do by adding this to my pyproject.toml:

```
[tool.pyright]
reportMissingModuleSource = false
```

Do let me know if you encounter another way to prevent this.

**Comment by thekeviv** [comment] 2023-01-27 22:26
Thank you for explaining. I wish it was possible to only turn that warning off for solders and not all modules but it doesn't seem like that's possible (unless you add `# pyright: ignore` next to imports).

**Comment by raymondjacobson** [comment] 2023-07-24 22:03
+1 am seeing this as well. @thekeviv did you find any other solve?

**Comment by bhy** [comment] 2024-04-27 03:48
Hi, I just stumbled upon this issue and wanted to chime in on the root cause. If you look at the Python typing doc on [module public symbols](https://typing.readthedocs.io/en/latest/source/libraries.html#library-interface-public-and-private-symbols), it says the static type checking only understands a limited set of syntax for defining `__all__`. Since `solders` need to dynamically extend `__all__`, it may not be properly resolved.

**Comment by kevinheavey** [comment] 2024-04-27 13:14
Thanks @bhy. Do you have any thoughts on just making `__all__` include every module whether or not it's available? Not perfect but I'm wondering if that would be less disruptive for people

**Comment by bhy** [comment] 2024-05-13 08:00
> Thanks @bhy. Do you have any thoughts on just making `__all__` include every module whether or not it's available on the user's platform? Not perfect but I'm wondering if that would be less disruptive for people

Yes. I think it makes sense to make `__all__` static, since it is for checking code. When a module is not available, it could be an error raised at runtime during import, since that should be a building / configuration issue.
